-- Wavelength: complete schema, security and deck.
-- Generated by scripts/build-deploy-sql.sh from supabase/migrations/ + seed.sql.
-- Paste into the Supabase SQL editor and run once.

begin;


-- ===================================================================
-- 20260920000100_schema.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Wavelength: core schema
--
-- Design rule that governs this whole file: the hidden target NEVER lives in a
-- table that is published to Realtime. Supabase's postgres_changes RLS check is
-- row-level only and does not honour column privileges, so the WAL record for a
-- `rounds` UPDATE would carry a secret column to every subscriber even if a
-- REST SELECT of it were revoked. The secret therefore lives in its own
-- `private` schema, which PostgREST cannot address at all.
-- ---------------------------------------------------------------------------

create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from anon, authenticated, public;
grant usage on schema private to service_role;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type team_side   as enum ('a', 'b');
create type room_status as enum ('lobby', 'in_game', 'finished');
create type round_phase as enum ('clue', 'guess', 'prediction', 'reveal', 'complete');
create type lr_side     as enum ('left', 'right');

-- Positions are stored as integer steps on the engine's 2000-step grid, not as
-- floats. Scoring compares integers, so this keeps the database and the
-- TypeScript engine in exact agreement with no rounding to reconcile.
create domain dial_position as smallint check (value between 0 and 2000);

-- ---------------------------------------------------------------------------
-- rooms
-- ---------------------------------------------------------------------------

create table public.rooms (
  id             uuid primary key default gen_random_uuid(),
  code           text not null,
  status         room_status not null default 'lobby',
  host_player_id uuid,
  winning_score  smallint not null default 10 check (winning_score between 1 and 50),
  created_at     timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  -- Unambiguous alphabet: no I, O, 0 or 1 to misread over a video call.
  constraint rooms_code_format check (code ~ '^[A-HJ-NP-Z2-9]{6}$')
);

-- A code is only reserved while the room is live; finished rooms release it.
create unique index rooms_code_live_uidx on public.rooms (code) where status <> 'finished';
create index rooms_last_active_idx on public.rooms (last_active_at);

-- ---------------------------------------------------------------------------
-- players
-- ---------------------------------------------------------------------------

create table public.players (
  id           uuid primary key default gen_random_uuid(),
  room_id      uuid not null references public.rooms(id) on delete cascade,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 24),
  team         team_side,
  is_host      boolean not null default false,
  -- Append-only psychic rotation order within a team.
  seat_order   integer not null,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  left_at      timestamptz
);

create index players_room_idx on public.players (room_id) where left_at is null;
create unique index players_seat_uidx
  on public.players (room_id, team, seat_order)
  where team is not null and left_at is null;

alter table public.rooms
  add constraint rooms_host_fk foreign key (host_player_id)
  references public.players(id) on delete set null;

-- Session tokens are per-player secrets, so they get the same treatment as the
-- target: out of any table that Realtime publishes.
create table private.player_sessions (
  player_id    uuid primary key references public.players(id) on delete cascade,
  token_hash   bytea not null unique,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- spectrum cards (public reference content)
-- ---------------------------------------------------------------------------

create table public.spectrum_cards (
  id          text primary key,
  left_label  text not null check (char_length(btrim(left_label)) > 0),
  right_label text not null check (char_length(btrim(right_label)) > 0),
  deck        text not null default 'base',
  enabled     boolean not null default true
);

create unique index spectrum_cards_pair_uidx
  on public.spectrum_cards (lower(left_label), lower(right_label));

-- ---------------------------------------------------------------------------
-- games
-- ---------------------------------------------------------------------------

create table public.games (
  id            uuid primary key default gen_random_uuid(),
  room_id       uuid not null references public.rooms(id) on delete cascade,
  score_a       smallint not null default 0 check (score_a >= 0),
  score_b       smallint not null default 0 check (score_b >= 0),
  starting_team team_side not null,
  status        room_status not null default 'in_game',
  winner        team_side,
  -- 0 = regulation play. >0 = the nth sudden-death round. Mirrors the engine's
  -- nullable SuddenDeathState rather than a boolean flag.
  sudden_death_index  smallint not null default 0 check (sudden_death_index >= 0),
  sudden_death_turns  smallint not null default 0 check (sudden_death_turns between 0 and 2),
  sudden_death_pts_a  smallint not null default 0,
  sudden_death_pts_b  smallint not null default 0,
  created_at    timestamptz not null default now(),
  ended_at      timestamptz
);

create unique index games_room_active_uidx on public.games (room_id) where status = 'in_game';

-- Cards already drawn this game, so a spectrum never repeats.
create table public.game_used_cards (
  game_id uuid not null references public.games(id) on delete cascade,
  card_id text not null references public.spectrum_cards(id),
  primary key (game_id, card_id)
);

-- ---------------------------------------------------------------------------
-- rounds  (PUBLIC — contains no secret while the round is live)
-- ---------------------------------------------------------------------------

create table public.rounds (
  id                uuid primary key default gen_random_uuid(),
  game_id           uuid not null references public.games(id) on delete cascade,
  room_id           uuid not null references public.rooms(id) on delete cascade,
  round_number      integer not null check (round_number > 0),
  active_team       team_side not null,
  psychic_player_id uuid not null references public.players(id) on delete restrict,
  card_id           text not null references public.spectrum_cards(id),

  phase    round_phase not null default 'clue',
  clue     text check (clue is null or char_length(btrim(clue)) between 1 and 120),
  clue_at  timestamptz,

  needle_controller_id uuid references public.players(id) on delete set null,
  -- Written once, at lock. In-flight dragging is broadcast, never persisted.
  needle_position      dial_position,
  needle_locked_at     timestamptz,

  prediction    lr_side,
  prediction_by uuid references public.players(id) on delete set null,
  prediction_at timestamptz,

  -- All null until the reveal transaction. This is what makes the realtime
  -- payload safe: there is no secret in the row to leak.
  revealed_target dial_position,
  active_points   smallint check (active_points in (0, 2, 3, 4)),
  opponent_points smallint check (opponent_points in (0, 1)),
  revealed_at     timestamptz,

  -- Published at round creation: sha256(nonce || target). Lets a client verify
  -- afterwards that the server did not move the target once it saw the needle.
  target_commitment bytea not null,

  created_at timestamptz not null default now(),

  constraint rounds_clue_present_after_clue_phase
    check (phase = 'clue' or clue is not null),
  constraint rounds_needle_present_after_guess
    check (phase in ('clue', 'guess') or needle_position is not null),
  constraint rounds_prediction_present_after_prediction
    check (phase in ('clue', 'guess', 'prediction') or prediction is not null),
  constraint rounds_reveal_is_all_or_nothing
    check ((phase in ('reveal', 'complete'))
           = (revealed_target is not null and active_points is not null))
);

create unique index rounds_game_number_uidx on public.rounds (game_id, round_number);
create index rounds_room_idx on public.rounds (room_id);

alter table public.games
  add column current_round_id uuid references public.rounds(id) on delete set null;

-- ---------------------------------------------------------------------------
-- THE SECRET
-- ---------------------------------------------------------------------------

create table private.round_targets (
  round_id      uuid primary key references public.rounds(id) on delete cascade,
  target_center dial_position not null,
  -- 16 random bytes, so the published commitment cannot be brute-forced even
  -- though target_center has only ~1750 possible values.
  nonce         bytea not null check (octet_length(nonce) >= 16),
  created_at    timestamptz not null default now()
);

-- Defence in depth. The real barrier is that `private` is not an exposed
-- schema and neither anon nor authenticated holds any grant on it; RLS with no
-- permissive policy is simply a third lock on the same door.
alter table private.round_targets enable row level security;
alter table private.round_targets force row level security;
alter table private.player_sessions enable row level security;
alter table private.player_sessions force row level security;

grant select, insert, update, delete on private.round_targets  to service_role;
grant select, insert, update, delete on private.player_sessions to service_role;

-- ===================================================================
-- 20260920000200_security.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Wavelength: grants, row level security, and the realtime publication
--
-- The security model in one line: browsers can READ their own room and write
-- NOTHING. Every mutation goes through a Next.js route handler holding the
-- service role key, which validates phase, actor and team before touching a
-- row.
--
-- Grants are the real boundary here, not policies. A policy is a filter you
-- have to get right; an absent grant is a wall.
-- ---------------------------------------------------------------------------

-- Start from deny. Supabase grants broadly to anon/authenticated by default.
revoke all on all tables    in schema public from anon, authenticated;
revoke all on all functions in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;

-- Read-only, and only these tables. `anon` is granted nothing at all: a bare
-- anon key is useless against this project until it is exchanged for a
-- room-scoped player token.
grant select on
  public.rooms,
  public.players,
  public.games,
  public.rounds,
  public.game_used_cards,
  public.spectrum_cards
to authenticated;

-- service_role is the only writer. Supabase grants it these by default, but
-- state them explicitly: the `revoke all ... from anon, authenticated` above is
-- easy to widen by accident, and a project restored from a dump should not
-- depend on defaults for the role that runs every mutation.
grant usage on schema public to service_role;
grant all privileges on all tables    in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant all privileges on all functions in schema public to service_role;
alter default privileges in schema public grant all on tables    to service_role;
alter default privileges in schema public grant all on sequences to service_role;

-- No INSERT/UPDATE/DELETE to anyone but service_role. Note there are no write
-- policies below either, so even a future accidental `grant insert` would hit
-- RLS default-deny rather than silently opening a hole.

-- ---------------------------------------------------------------------------
-- Room scoping
--
-- Players are anonymous: there is no auth.users row. The server mints a
-- short-lived HS256 JWT carrying the player's room, and PostgREST/Realtime
-- validate it because it is signed with the project's JWT secret. RLS then
-- reads the claim.
-- ---------------------------------------------------------------------------

create or replace function public.jwt_room_id()
returns uuid
language sql
stable
security invoker
set search_path = ''
as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'room_id', '')::uuid
$$;

grant execute on function public.jwt_room_id() to authenticated;

alter table public.rooms           enable row level security;
alter table public.players         enable row level security;
alter table public.games           enable row level security;
alter table public.rounds          enable row level security;
alter table public.game_used_cards enable row level security;
alter table public.spectrum_cards  enable row level security;

create policy rooms_select_own_room on public.rooms
  for select to authenticated
  using (id = public.jwt_room_id());

create policy players_select_own_room on public.players
  for select to authenticated
  using (room_id = public.jwt_room_id());

create policy games_select_own_room on public.games
  for select to authenticated
  using (room_id = public.jwt_room_id());

create policy rounds_select_own_room on public.rounds
  for select to authenticated
  using (room_id = public.jwt_room_id());

create policy game_used_cards_select_own_room on public.game_used_cards
  for select to authenticated
  using (exists (
    select 1 from public.games g
    where g.id = game_used_cards.game_id
      and g.room_id = public.jwt_room_id()
  ));

-- Card text is public game content, not per-room.
create policy spectrum_cards_select_enabled on public.spectrum_cards
  for select to authenticated
  using (enabled);

-- ---------------------------------------------------------------------------
-- Realtime publication
--
-- Explicit opt-in, one table at a time. `private.round_targets` and
-- `private.player_sessions` are deliberately absent and must stay that way:
-- adding them would put their contents into WAL records that Realtime fans out
-- to subscribers, which no column grant can prevent.
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.games;
alter publication supabase_realtime add table public.rounds;

-- Needed so subscribers receive the previous row on updates and deletes.
-- Safe only because none of these tables ever holds a pre-reveal secret.
alter table public.rooms   replica identity full;
alter table public.players replica identity full;
alter table public.games   replica identity full;
alter table public.rounds  replica identity full;

-- ---------------------------------------------------------------------------
-- A standing check against the mistake this design is built to prevent.
-- Fails the migration if a private table is ever added to the publication.
-- ---------------------------------------------------------------------------

do $$
declare
  leaked text;
begin
  select string_agg(format('%I.%I', schemaname, tablename), ', ')
    into leaked
    from pg_publication_tables
   where pubname = 'supabase_realtime'
     and schemaname = 'private';

  if leaked is not null then
    raise exception
      'Private tables are published to Realtime: %. Secrets must never be in the publication.',
      leaked;
  end if;
end;
$$;

-- ===================================================================
-- 20260920000300_secret_access.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Controlled access to the secret schema.
--
-- `private` is deliberately NOT in PostgREST's exposed schemas, which is one of
-- the three barriers protecting the target. But that cuts both ways: the
-- server's own PostgREST client cannot reach it either, not even with the
-- service role key.
--
-- So access goes through SECURITY DEFINER functions that live in `public`
-- (addressable) but whose EXECUTE privilege is granted ONLY to service_role.
-- This keeps every barrier: the schema stays unexposed, anon and authenticated
-- still hold no grant on it, and it stays out of the realtime publication.
--
-- Each function is minimal and does one thing, so the amount of code running
-- with elevated rights stays small enough to audit at a glance.
-- ---------------------------------------------------------------------------

-- --- write the target for a new round --------------------------------------

create or replace function public.place_round_target(
  p_round_id uuid,
  p_target   smallint,
  p_nonce    bytea
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into private.round_targets (round_id, target_center, nonce)
  values (p_round_id, p_target, p_nonce);
end;
$$;

-- --- read it back, for the Psychic ------------------------------------------

create or replace function public.read_round_target(p_round_id uuid)
returns smallint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_target smallint;
begin
  select target_center into v_target
    from private.round_targets
   where round_id = p_round_id;
  return v_target;
end;
$$;

-- --- read target and nonce together, for the reveal -------------------------

create or replace function public.take_round_target(p_round_id uuid)
returns table (target_center smallint, nonce bytea)
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- target_center is the `dial_position` DOMAIN, not a bare smallint, and
  -- RETURNS TABLE compares the two strictly — without this cast Postgres
  -- raises 42804 at call time. (read_round_target avoids it only because
  -- SELECT INTO casts implicitly on assignment.)
  return query
    select t.target_center::smallint, t.nonce
      from private.round_targets t
     where t.round_id = p_round_id;
end;
$$;

-- --- session tokens ---------------------------------------------------------

create or replace function public.create_player_session(
  p_player_id  uuid,
  p_token_hash bytea
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into private.player_sessions (player_id, token_hash)
  values (p_player_id, p_token_hash)
  on conflict (player_id) do update
    set token_hash = excluded.token_hash,
        last_seen_at = now();
end;
$$;

create or replace function public.resolve_player_session(p_token_hash bytea)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player_id uuid;
begin
  select player_id into v_player_id
    from private.player_sessions
   where token_hash = p_token_hash;

  if v_player_id is not null then
    update private.player_sessions
       set last_seen_at = now()
     where player_id = v_player_id;
  end if;

  return v_player_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Lock every one of them to service_role.
--
-- Without these revokes a SECURITY DEFINER function is callable by anyone
-- holding the anon key, and the entire protection would be the function body.
-- ---------------------------------------------------------------------------

do $$
declare
  fn text;
begin
  foreach fn in array array[
    'public.place_round_target(uuid, smallint, bytea)',
    'public.read_round_target(uuid)',
    'public.take_round_target(uuid)',
    'public.create_player_session(uuid, bytea)',
    'public.resolve_player_session(bytea)'
  ]
  loop
    execute format('revoke all on function %s from public, anon, authenticated', fn);
    execute format('grant execute on function %s to service_role', fn);
  end loop;
end;
$$;

-- ===================================================================
-- 20260921000100_round_recovery.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Recovery when the Psychic leaves before giving their clue.
--
-- The round cannot simply continue: the departing player saw the target and
-- may still be in the room watching. So the target is re-rolled along with the
-- handover, and a fresh commitment is published.
--
-- Same access rule as the other secret functions: SECURITY DEFINER, reachable
-- only by service_role.
-- ---------------------------------------------------------------------------

create or replace function public.replace_round_target(
  p_round_id uuid,
  p_target   smallint,
  p_nonce    bytea
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into private.round_targets (round_id, target_center, nonce)
  values (p_round_id, p_target, p_nonce)
  on conflict (round_id) do update
    set target_center = excluded.target_center,
        nonce         = excluded.nonce,
        created_at    = now();
end;
$$;

revoke all on function public.replace_round_target(uuid, smallint, bytea)
  from public, anon, authenticated;
grant execute on function public.replace_round_target(uuid, smallint, bytea)
  to service_role;

-- ===================================================================
-- 20260921000200_coop.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Co-op: everyone on one team, nobody to call left or right.
--
-- The reveal previously required a left/right call to exist. In co-op there
-- is no opposing team to make one, so the round goes straight from the locked
-- guess to the reveal with prediction left null.
--
-- The remaining reveal constraint still holds the important invariant: a
-- revealed round must have both a target and a score.
-- ---------------------------------------------------------------------------

alter table public.rounds
  drop constraint if exists rounds_prediction_present_after_prediction;

comment on column public.rounds.prediction is
  'The opposing team''s left/right call. Null in co-op, where there is no opposing team to make one.';

-- ===================================================================
-- 20260921000300_free_for_all.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Free-for-all: no teams, everyone places their own needle.
--
-- A departure from the printed rules, which are a team game. One Psychic gives
-- a clue, every other player commits their own guess, and each scores their
-- own result — the Psychic taking the average of the rest, so a clue that
-- lands the room near the target is worth giving.
--
-- Everyone sits on team 'a' internally. Teams are not modelled away entirely
-- because `rounds.active_team` and the psychic rotation are built on them, and
-- a single-sided game is a valid configuration of that machinery rather than a
-- special case bolted beside it.
-- ---------------------------------------------------------------------------

-- Per-player running total.
alter table public.players
  add column if not exists score smallint not null default 0 check (score >= 0);

-- One committed guess per player per round.
create table if not exists public.round_guesses (
  round_id   uuid not null references public.rounds(id) on delete cascade,
  player_id  uuid not null references public.players(id) on delete cascade,
  position   dial_position not null,
  -- Filled at the reveal, so the result is inspectable per player afterwards.
  points     smallint check (points in (0, 2, 3, 4)),
  created_at timestamptz not null default now(),
  primary key (round_id, player_id)
);

create index if not exists round_guesses_round_idx on public.round_guesses (round_id);

-- Readable by the room, like every other public table. The guess is not a
-- secret — it is the whole point that everyone sees where you landed — but it
-- is only published once the round reveals, because the server writes points
-- at that moment and clients render from the bootstrap payload.
alter table public.round_guesses enable row level security;

create policy round_guesses_select_own_room on public.round_guesses
  for select to authenticated
  using (exists (
    select 1 from public.rounds r
    where r.id = round_guesses.round_id
      and r.room_id = public.jwt_room_id()
  ));

grant select on public.round_guesses to authenticated;
grant all privileges on public.round_guesses to service_role;

alter publication supabase_realtime add table public.round_guesses;
alter table public.round_guesses replica identity full;

-- A free-for-all round has no single needle of record, so the constraint
-- requiring one after the guessing phase no longer holds.
alter table public.rounds
  drop constraint if exists rounds_needle_present_after_guess;

comment on table public.round_guesses is
  'One committed needle per player per round, in free-for-all. Contains no secret: guesses are public once revealed, and the target lives in private.round_targets.';

-- ===================================================================
-- 20260921000400_reveal_constraint.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Loosen the reveal constraint for free-for-all.
--
-- It required active_points to be set whenever a round reached 'reveal', which
-- was right for the team game: the active team always scored something, even
-- if zero. Free-for-all has no team score at all — points live per player in
-- round_guesses — so the round could never legally reveal.
--
-- The invariant worth keeping is narrower: a revealed round must have a
-- revealed target. That is what makes the reveal meaningful, and what stops a
-- round claiming to be over while the answer is still hidden.
-- ---------------------------------------------------------------------------

alter table public.rounds
  drop constraint if exists rounds_reveal_is_all_or_nothing;

alter table public.rounds
  add constraint rounds_revealed_has_a_target
  check ((phase in ('reveal', 'complete')) = (revealed_target is not null));

-- ===================================================================
-- 20260922000100_vote_skip.sql
-- ===================================================================

-- ---------------------------------------------------------------------------
-- Vote-skip: the room can throw away a card it cannot work with.
--
-- Some spectrums are simply unclueable for the Psychic who drew them. Before
-- this the only escape was restarting the whole game, so people sat on a dead
-- card or quit. A strict majority now deals a replacement.
--
-- The replacement keeps the SAME round row: same id, same round_number, same
-- Psychic. That is partly the rule we want — drawing a bad card should not
-- cost anyone their turn — and partly what the schema already insists on,
-- since `rounds_game_number_uidx` is unique on (game_id, round_number) and
-- `round_phase` has no value for an abandoned round. Rewriting the card in
-- place needs neither a new enum value nor a relaxed constraint.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- the votes
-- ---------------------------------------------------------------------------

create table if not exists public.round_skip_votes (
  round_id   uuid not null references public.rounds(id) on delete cascade,
  player_id  uuid not null references public.players(id) on delete cascade,
  -- The card the vote was cast against, which is what makes rewriting the
  -- round in place safe. A reroll changes `rounds.card_id`, and that alone
  -- makes every vote for the previous card inert — including one that was
  -- still in flight when the card changed. Without this column such a vote
  -- would count towards binning a replacement its author never saw.
  card_id    text not null references public.spectrum_cards(id),
  created_at timestamptz not null default now(),
  primary key (round_id, player_id, card_id)
);

create index if not exists round_skip_votes_round_idx
  on public.round_skip_votes (round_id, card_id);

-- Same posture as round_guesses: no secret here, and the room may read it —
-- watching the tally move is what makes this a vote rather than a silent host
-- power. The browser never queries Supabase directly, so in practice this is
-- defence in depth behind the service-role routes.
alter table public.round_skip_votes enable row level security;

create policy round_skip_votes_select_own_room on public.round_skip_votes
  for select to authenticated
  using (exists (
    select 1 from public.rounds r
    where r.id = round_skip_votes.round_id
      and r.room_id = public.jwt_room_id()
  ));

grant select on public.round_skip_votes to authenticated;
grant all privileges on public.round_skip_votes to service_role;

-- Deliberately NOT added to supabase_realtime. Clients learn that the tally
-- moved from the room broadcast and re-read the bootstrap payload, the way
-- they learn about everything else; publishing the rows as well would put a
-- second serialisation path in front of data that has one already.

comment on table public.round_skip_votes is
  'Standing votes to discard the card a round is showing. Keyed by card, so a reroll invalidates the previous round''s votes without deleting them.';

-- ---------------------------------------------------------------------------
-- the reroll
-- ---------------------------------------------------------------------------

-- SECURITY DEFINER for the same reason as the other secret functions: the
-- target lives in `private`, which PostgREST cannot address even for
-- service_role. EXECUTE is granted to service_role alone, below.
create or replace function public.reroll_round_card(
  p_round_id    uuid,
  p_expect_card text,
  p_card_id     text,
  p_target      smallint,
  p_nonce       bytea,
  p_commitment  bytea
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_game_id uuid;
begin
  -- Compare-and-swap on the card. Two players can cast the deciding vote at
  -- the same instant; only the one whose expected card is still on the round
  -- wins, and the loser is told `false` rather than skipping a second card
  -- that nobody had a chance to read.
  --
  -- The phase clause does the same job against a clue already in flight: if
  -- the Psychic's clue landed first the round has moved to 'guess' and the
  -- skip is simply too late.
  update public.rounds
     set card_id           = p_card_id,
         target_commitment = p_commitment
   where id      = p_round_id
     and phase   = 'clue'
     and card_id = p_expect_card
  returning game_id into v_game_id;

  if v_game_id is null then
    return false;
  end if;

  -- The target and its commitment have to move together or the published
  -- commitment is a lie, and the one thing it exists to prove — that the
  -- server did not move the target after seeing the needles — stops being
  -- provable. Two round trips from the server could be interrupted between
  -- them; one function cannot.
  insert into private.round_targets (round_id, target_center, nonce)
  values (p_round_id, p_target, p_nonce)
  on conflict (round_id) do update
    set target_center = excluded.target_center,
        nonce         = excluded.nonce,
        created_at    = now();

  -- The skipped card was already recorded as used at round creation and stays
  -- that way, so a card the room rejected cannot come back this game. The
  -- replacement is recorded now, for the same reason.
  insert into public.game_used_cards (game_id, card_id)
  values (v_game_id, p_card_id)
  on conflict do nothing;

  return true;
end;
$$;

revoke all on function
  public.reroll_round_card(uuid, text, text, smallint, bytea, bytea)
  from public, anon, authenticated;
grant execute on function
  public.reroll_round_card(uuid, text, text, smallint, bytea, bytea)
  to service_role;

-- ===================================================================
-- seed.sql
-- ===================================================================

-- Generated by scripts/generate-seed.mts. Do not edit by hand.
-- Run `pnpm seed:generate` after changing src/lib/game/deck.ts.
--
-- 120 original spectrums. The printed text of the
-- commercial game is copyrighted and is not reproduced; see docs/deck-format.md
-- for loading your own.

insert into public.spectrum_cards (id, left_label, right_label, deck) values
  ('c001', 'Underrated', 'Overrated', 'base'),
  ('c002', 'Forgettable', 'Unforgettable', 'base'),
  ('c003', 'Guilty pleasure', 'Openly enjoyed', 'base'),
  ('c004', 'Acquired taste', 'Universally loved', 'base'),
  ('c005', 'Style over substance', 'Substance over style', 'base'),
  ('c006', 'Cult classic', 'Mainstream hit', 'base'),
  ('c007', 'Ages badly', 'Ages well', 'base'),
  ('c008', 'Background noise', 'Demands your attention', 'base'),
  ('c009', 'Hot', 'Cold', 'base'),
  ('c010', 'Soft', 'Hard', 'base'),
  ('c011', 'Fragile', 'Indestructible', 'base'),
  ('c012', 'Lightweight', 'Heavy', 'base'),
  ('c013', 'Quiet', 'Loud', 'base'),
  ('c014', 'Smooth', 'Rough', 'base'),
  ('c015', 'Tiny', 'Enormous', 'base'),
  ('c016', 'Dull', 'Sharp', 'base'),
  ('c017', 'Normal thing to own', 'Weird thing to own', 'base'),
  ('c018', 'Rude', 'Polite', 'base'),
  ('c019', 'Casual outfit', 'Formal outfit', 'base'),
  ('c020', 'Fine to do alone', 'Strange to do alone', 'base'),
  ('c021', 'Private matter', 'Everyone''s business', 'base'),
  ('c022', 'Easy to forgive', 'Unforgivable', 'base'),
  ('c023', 'Modest', 'Showing off', 'base'),
  ('c024', 'Socially acceptable lie', 'Serious betrayal', 'base'),
  ('c025', 'Effortless', 'Exhausting', 'base'),
  ('c026', 'Anyone can do it', 'Takes real talent', 'base'),
  ('c027', 'Temporary fix', 'Permanent fix', 'base'),
  ('c028', 'Chore', 'Treat', 'base'),
  ('c029', 'Beginner friendly', 'Steep learning curve', 'base'),
  ('c030', 'Quick to learn', 'A lifetime to master', 'base'),
  ('c031', 'Harmless', 'Dangerous', 'base'),
  ('c032', 'Safe bet', 'Wild gamble', 'base'),
  ('c033', 'Mild inconvenience', 'Total disaster', 'base'),
  ('c034', 'Irrational fear', 'Reasonable fear', 'base'),
  ('c035', 'Worth the risk', 'Never worth it', 'base'),
  ('c036', 'Snack', 'Proper meal', 'base'),
  ('c037', 'Bland', 'Intense flavour', 'base'),
  ('c038', 'Comfort food', 'Fine dining', 'base'),
  ('c039', 'Better cold', 'Better hot', 'base'),
  ('c040', 'Healthy', 'Terrible for you', 'base'),
  ('c041', 'Ancient', 'Brand new', 'base'),
  ('c042', 'A phase', 'Here to stay', 'base'),
  ('c043', 'Takes a second', 'Takes all day', 'base'),
  ('c044', 'Old-fashioned', 'Ahead of its time', 'base'),
  ('c045', 'Nostalgic', 'Futuristic', 'base'),
  ('c046', 'Cheap', 'Expensive', 'base'),
  ('c047', 'Waste of money', 'Worth every penny', 'base'),
  ('c048', 'Necessity', 'Luxury', 'base'),
  ('c049', 'Disposable', 'Heirloom', 'base'),
  ('c050', 'Villain', 'Hero', 'base'),
  ('c051', 'Follower', 'Leader', 'base'),
  ('c052', 'Book smart', 'Street smart', 'base'),
  ('c053', 'Introvert', 'Extrovert', 'base'),
  ('c054', 'Predictable', 'Full of surprises', 'base'),
  ('c055', 'Bad influence', 'Role model', 'base'),
  ('c056', 'Overthinking it', 'Not thinking at all', 'base'),
  ('c057', 'A want', 'A need', 'base'),
  ('c058', 'Boring but useful', 'Useless but fun', 'base'),
  ('c059', 'Clean', 'Filthy', 'base'),
  ('c060', 'A rumour', 'Established fact', 'base'),
  ('c061', 'Silly', 'Deadly serious', 'base'),
  ('c062', 'Cursed object', 'Lucky charm', 'base'),
  ('c063', 'Style you''d wear', 'Costume', 'base'),
  ('c064', 'A good sequel', 'A cash grab', 'base'),
  ('c065', 'Low budget', 'Blockbuster', 'base'),
  ('c066', 'Reads the book', 'Waits for the film', 'base'),
  ('c067', 'A song you skip', 'A song you replay', 'base'),
  ('c068', 'Fits in a tweet', 'Needs an essay', 'base'),
  ('c069', 'Aimed at kids', 'Strictly for adults', 'base'),
  ('c070', 'Slow burn', 'Instant hook', 'base'),
  ('c071', 'Tourist trap', 'Hidden gem', 'base'),
  ('c072', 'Somewhere you''d visit', 'Somewhere you''d live', 'base'),
  ('c073', 'Cramped', 'Spacious', 'base'),
  ('c074', 'Middle of nowhere', 'City centre', 'base'),
  ('c075', 'Relaxing holiday', 'Gruelling expedition', 'base'),
  ('c076', 'A job', 'A calling', 'base'),
  ('c077', 'Thankless work', 'All the glory', 'base'),
  ('c078', 'Hobby', 'Obsession', 'base'),
  ('c079', 'Sensible career', 'Wild gamble', 'base'),
  ('c080', 'Works alone', 'Needs a team', 'base'),
  ('c081', 'Automatable', 'Irreplaceably human', 'base'),
  ('c082', 'Calming', 'Stressful', 'base'),
  ('c083', 'Mildly annoying', 'Blindingly infuriating', 'base'),
  ('c084', 'Cringe', 'Genuinely cool', 'base'),
  ('c085', 'Sad', 'Joyful', 'base'),
  ('c086', 'Embarrassing in private', 'Embarrassing in public', 'base'),
  ('c087', 'Cosy', 'Bleak', 'base'),
  ('c088', 'Underwhelming', 'Lives up to the hype', 'base'),
  ('c089', 'A habit', 'An addiction', 'base'),
  ('c090', 'Easy to start', 'Hard to quit', 'base'),
  ('c091', 'Worth doing properly', 'Just get it done', 'base'),
  ('c092', 'Plans everything', 'Total improviser', 'base'),
  ('c093', 'Arrives early', 'Always late', 'base'),
  ('c094', 'Keeps everything', 'Throws it all out', 'base'),
  ('c095', 'Overengineered', 'Barely works', 'base'),
  ('c096', 'Everyone owns one', 'Almost nobody owns one', 'base'),
  ('c097', 'Obsolete', 'Cutting edge', 'base'),
  ('c098', 'Ugly but works', 'Beautiful but useless', 'base'),
  ('c099', 'Repairable', 'Throw it away', 'base'),
  ('c100', 'A toy', 'A serious tool', 'base'),
  ('c101', 'Cute animal', 'Terrifying animal', 'base'),
  ('c102', 'Good pet', 'Terrible pet', 'base'),
  ('c103', 'Common', 'Rare', 'base'),
  ('c104', 'Tame', 'Wild', 'base'),
  ('c105', 'Survives anything', 'Dies immediately', 'base'),
  ('c106', 'Superstition', 'Science', 'base'),
  ('c107', 'A white lie', 'A real crime', 'base'),
  ('c108', 'Selfish', 'Selfless', 'base'),
  ('c109', 'Morally grey', 'Clearly wrong', 'base'),
  ('c110', 'Nobody''s fault', 'Entirely your fault', 'base'),
  ('c111', 'Deserved', 'Unfair', 'base'),
  ('c112', 'Trivial', 'Life-changing', 'base'),
  ('c113', 'Affects one person', 'Affects everyone', 'base'),
  ('c114', 'Easily undone', 'Irreversible', 'base'),
  ('c115', 'Local problem', 'Global crisis', 'base'),
  ('c116', 'Luck', 'Skill', 'base'),
  ('c117', 'Friendly game', 'Friendship-ending game', 'base'),
  ('c118', 'Fun to lose', 'Only fun to win', 'base'),
  ('c119', 'Simple rules', 'Rulebook the size of a novel', 'base'),
  ('c120', 'Spectator sport', 'Only fun to play', 'base')
on conflict (id) do update
  set left_label  = excluded.left_label,
      right_label = excluded.right_label,
      deck        = excluded.deck;

commit;
