#!/usr/bin/env bash
# Concatenate the migrations and seed into one transactional script for the
# Supabase SQL editor, so a fresh project is one paste rather than four.
set -euo pipefail
cd "$(dirname "$0")/.."

{
  printf -- "-- Wavelength: complete schema, security and deck.\n"
  printf -- "-- Generated by scripts/build-deploy-sql.sh from supabase/migrations/ + seed.sql.\n"
  printf -- "-- Paste into the Supabase SQL editor and run once.\n\nbegin;\n\n"
  for f in supabase/migrations/*.sql; do
    printf -- "\n-- ===================================================================\n-- %s\n-- ===================================================================\n\n" "$(basename "$f")"
    cat "$f"
  done
  printf -- "\n-- ===================================================================\n-- seed.sql\n-- ===================================================================\n\n"
  cat supabase/seed.sql
  printf -- "\ncommit;\n"
} > supabase/deploy.sql

echo "Wrote supabase/deploy.sql ($(wc -l < supabase/deploy.sql) lines)"
