#!/usr/bin/env bash
# Bring up a Supabase-compatible stack without Docker.
#
# Supabase's REST API is PostgREST, and its "keys" are ordinary JWTs naming a
# Postgres role. So Postgres + PostgREST + a path-rewriting proxy is enough to
# exercise every route handler, every grant and every RLS policy for real.
#
# What this does NOT give you is Realtime, which is a separate service.
# Subscriptions still need a real Supabase project.
#
#   brew install postgresql@17 postgrest
#   brew services start postgresql@17
#   ./scripts/dev-stack.sh
set -euo pipefail

export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"
SECRET="${SUPABASE_JWT_SECRET:-local-dev-jwt-secret-at-least-32-chars-long}"

cleanup() {
  echo
  echo "==> Stopping"
  pkill -f "postgrest supabase/local/postgrest.conf" 2>/dev/null || true
  pkill -f "scripts/rest-proxy.mjs" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cleanup
sleep 1

echo "==> Database"
./scripts/db-test.sh > /dev/null
echo "    migrations applied, deck seeded, security suite passed"

echo "==> Keys"
KEYS=$(node scripts/make-keys.mjs "$SECRET")
ANON=$(printf '%s' "$KEYS" | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>console.log(JSON.parse(s).anon))")
SERVICE=$(printf '%s' "$KEYS" | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>console.log(JSON.parse(s).service_role))")

cat > supabase/local/postgrest.conf <<CONF
# Generated by scripts/dev-stack.sh.
# db-schemas lists only 'public' — 'private' is deliberately absent, exactly as
# on a real Supabase project. That is what makes the PGRST106 refusal testable.
db-uri = "postgres://$(whoami)@127.0.0.1:5432/wavelength_test"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "$SECRET"
server-port = 3001
log-level = "error"
CONF

cat > .env.local <<ENV
# Generated by scripts/dev-stack.sh — a local PostgREST stack, not real Supabase.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE
SUPABASE_JWT_SECRET=$SECRET
ENV
echo "    .env.local written"

echo "==> PostgREST"
postgrest supabase/local/postgrest.conf > /tmp/wavelength-postgrest.log 2>&1 &
echo "==> Proxy"
node scripts/rest-proxy.mjs > /tmp/wavelength-proxy.log 2>&1 &
sleep 3

echo
echo "Stack is up. In another terminal:"
echo "    pnpm dev"
echo "    node scripts/e2e-api.mjs"
echo
echo "Ctrl-C to stop."
while true; do sleep 3600; done
