/**
 * Regenerate supabase/seed.sql from the TypeScript deck, so the database and
 * the engine can never disagree about what a card id means.
 *
 *   pnpm seed:generate
 */
import { writeFileSync } from "node:fs";

import { SPECTRUM_DECK } from "../src/lib/game/deck.ts";

const quote = (value: string): string => `'${value.replaceAll("'", "''")}'`;

const rows = SPECTRUM_DECK.map(
  (card) => `  (${quote(card.id)}, ${quote(card.left)}, ${quote(card.right)}, 'base')`,
).join(",\n");

const sql = `-- Generated by scripts/generate-seed.mts. Do not edit by hand.
-- Run \`pnpm seed:generate\` after changing src/lib/game/deck.ts.
--
-- ${SPECTRUM_DECK.length} original spectrums. The printed text of the
-- commercial game is copyrighted and is not reproduced; see docs/deck-format.md
-- for loading your own.

insert into public.spectrum_cards (id, left_label, right_label, deck) values
${rows}
on conflict (id) do update
  set left_label  = excluded.left_label,
      right_label = excluded.right_label,
      deck        = excluded.deck;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql with ${SPECTRUM_DECK.length} cards.`);
